yaml
name: Windows Runner

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Check Windows Version
        shell: pwsh
        run: |
          Get-ComputerInfo |
            Select-Object WindowsProductName, WindowsVersion, OsBuildNumber

      - name: Check User
        shell: pwsh
        run: |
          whoami
          hostname
          Get-Date
